# Models (Pydantic Schemas) for request and response validation

from pydantic import BaseModel

class ChatRequest(BaseModel):
    message: str # User should provide a message to the chatbot

class ChatResponse(BaseModel):
    reply: str # Chatbot's reply to the user
    tokens: list[str] # List of tokens generated by the NLP model