# Models (Pydantic Schemas) for request and response validation

from pydantic import BaseModel

class ChatMessage(BaseModel):
    role: str # Role of the message sender (e.g., "user" or "socrates")
    content: str # Content of the message
    
class ChatRequest(BaseModel):
    messages: list[ChatMessage] # User should provide a message to the chatbot

class ChatResponse(BaseModel):
    reply: str # Chatbot's reply to the user
    tokens: list[str] # List of tokens generated by the NLP model